version: '3.8'

services:

  taxi-server:
    build:
      context: ./server
      dockerfile: ../compose/production/server/Dockerfile
    command: gunicorn taxi.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
      - taxi-database
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/media/

  nginx:
    container_name: taxi-nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/media/
    ports:
      - 1337:80
      - 1338:30
    depends_on:
      - taxi-server

  taxi-redis:
    container_name: taxi-redis
    image: redis:7-alpine

  taxi-database:
    container_name: taxi-database
    image: postgres:15-alpine
    env_file:
      - ./.env
    expose:
      - 5432
    volumes:
      - taxi-database:/var/lib/postgresql/data

volumes:
  taxi-database:
  static_volume:
  media_volume:
  html_build:
